### ISSUE TITLE
 For TypeAsset, android “long” is not long enough

### ISSUE THREAD

**Issue by w2hhda** [plactal/EosCommander#10]
For TypeAsset, android “long” is not long enough,
when my token symbol name is "JUNGLE"， android long is not long enough,

I have modified it into a byte array.

private byte[] mAssetSymbol;

**Comment by swapnibble** [comment]
TypeAsset has been split to TypeAsset and TypeSymbol. ( commit 8886caf316131be385f2edfc0f36c31f97049ce3 )
