### ISSUE TITLE
TypeSymbol bug

### ISSUE THREAD

**Issue by guangxingmao** [plactal/EosCommander#12]
while i transfer eosdac token, i'l see the exception  of (precision should be <= " +18 + ": " + 68), 

TypeSymbol -> 
public short decimals() {
   return (short) (mValue & 0xFF);
}

**Comment by guangxingmao** [comment]
first balance = "0.0100 EOSDAC",

![2018-07-18 13 40 57](https://user-images.githubusercontent.com/19208420/42862186-021f1d48-8a91-11e8-9c45-9d18ee5b122a.png)

![2018-07-18 13 48 27](https://user-images.githubusercontent.com/19208420/42862257-4e0b34e4-8a91-11e8-99c5-e00184671524.png)
![2018-07-18 13 41 55](https://user-images.githubusercontent.com/19208420/42862271-61fd3268-8a91-11e8-9732-7354967e88ac.png)

Result,  result = "100. EOSDAC" ,
Error of "Missing decimal fraction after decimal point"
and the latest version is also such errors

**Comment by swapnibble** [comment]
fixed on 40c86d3f4eae67314344932938872abca043730a
