### ISSUE TITLE
How can I add this to my Android Studio project?

### ISSUE THREAD

**Issue by CosimoSguanci** [plactal/EosCommander#14]

**Comment by abhi3700** [comment]
I think they have not made it as package.

You have to use all the dependencies in any EOS dApp case.

**Comment by CosimoSguanci** [comment]
What do you mean by 'use all the dependencies' ?

**Comment by abhi3700** [comment]
check the [build.gradle file](https://github.com/plactal/EosCommander/blob/master/app/build.gradle)

**Comment by swapnibble** [comment]
add sources under data package. and check the dependencies from build.gradle
