### ISSUE TITLE
private key import bug

### ISSUE THREAD

**Issue by oday0311** [plactal/EosCommander#15]
when checking the checksum, the byte data is decode as Base58 , 
but the checkOne and checkTwo do not have Base58 convert, so may cause some checking fail . 

here is an example:
5HpZ2PpApoBnKQceLZ8jfKom413zSSqYQ63UGAYDTb2MyxLFt4c

 public static byte[] getBytesIfMatchedSha256(String base58Data,RefValue<Long> checksumRef ){
        byte[] data= Base58.decode( base58Data );

        return Arrays.copyOfRange(data, 1, data.length - 4);

        // offset 0은 제외, 뒤의 4바이트 제외하고, private key 를 뽑자

        /* checksum decode has bug. example ：

        Sha256 checkOne = Sha256.from( data, 0, data.length - 4 );
        Sha256 checkTwo = Sha256.from( checkOne.getBytes() );
        if ( checkTwo.equalsFromOffset( data, data.length - 4, 4)
                || checkOne.equalsFromOffset( data, data.length - 4, 4) ){

            if ( checksumRef != null ){
                checksumRef.data = BitUtils.uint32ToLong( data, data.length - 4);
            }

            return Arrays.copyOfRange(data, 1, data.length - 4);
        }

        throw new IllegalArgumentException("Invalid format, checksum mismatch");
        */
    }

**Comment by swapnibble** [comment]
It seems that you copied wrong key string. 
Valid wif format string is "5HpZ2PpApoBnKQceLZ8jfKom413zSSqYQ63UGAYDTb2MyxLFt4C" (notice that  last character is upper case 'C', not lower case 'c'. you tried lower case 'c' ).

keosd in eosio also says "invalid private key" for "5HpZ2PpApoBnKQceLZ8jfKom413zSSqYQ63UGAYDTb2MyxLFt4c" ( last character is lower case 'c' ).
