### ISSUE TITLE
rpc返回的签名和本地的签名不一致

### ISSUE THREAD

**Issue by guangxingmao** [plactal/EosCommander#6]
[
  {
    "ref_block_num": 63734,
    "ref_block_prefix": 517331098,
    "expiration": "2018-06-01T03:22:42",
    "actions": [
      {
        "account": "eosio",
        "name": "newaccount",
        "authorization": [
          {
            "actor": "alice",
            "permission": "active"
          }
        ],
        "data":"0000000000855c341042082184103a9301000000010002594a4d3c11b0573c7b4cf71e8f20245190bdf884aceb5da8b3bbf54dd76ed4ef0100000001000000010002594a4d3c11b0573c7b4cf71e8f20245190bdf884aceb5da8b3bbf54dd76ed4ef01000000"
      }
    ],
    "signatures": []
  },
  [
    "EOS78nndF91Wa1QWSzykZ9RfoToT8b6taKXpwbRQmEQfzSPYNBMnN"
  ],
  "706a7ddd808de9fc2b8879904f3b392256c83104c1d544b38302cc07d9fca477"
]

**Comment by swapnibble** [comment]
Signature is always different from each call. It's not a matter of remote or local.  
Source data of signature always change each time you request signature of an action(transaction) because of including reference block information.
